name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Собираем проект
      - name: Build project
        run: npm run build

      # 5. Публикуем на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Используем GitHub токен для аутентификации
          publish_dir: ./dist  # Путь к директории, которая будет опубликована на GitHub Pages
          user_name: 'github-actions'  # Имя пользователя
          user_email: 'github-actions@github.com'  # Электронная почта

      # 6. Отправка уведомления в Telegram (по желанию)
      - name: Send Telegram message
        if: success()  # Отправляем сообщение только при успешном деплое
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.VITE_TELEGRAM_CHAT_ID }} \
          -d text="Deployment completed successfully!"
        env:
          TELEGRAM_TOKEN: ${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.VITE_TELEGRAM_CHAT_ID }}
