name: Deploy Vite React Project to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug env variables
        run: |
          echo "Checking if env variables exist:"
          if [ -n "${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}" ]; then
            echo "VITE_TELEGRAM_BOT_TOKEN exists and is not empty"
            echo "First 4 characters of token: ${${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}:0:4}..."
          else
            echo "VITE_TELEGRAM_BOT_TOKEN is empty or not set"
          fi
          if [ -n "${{ secrets.VITE_TELEGRAM_CHAT_ID }}" ]; then
            echo "VITE_TELEGRAM_CHAT_ID exists and is not empty"
            echo "Chat ID value length: ${#${{ secrets.VITE_TELEGRAM_CHAT_ID }}}"
          else
            echo "VITE_TELEGRAM_CHAT_ID is empty or not set"
          fi

      - name: Install dependencies
        run: npm install

      - name: Create env file
        run: |
          touch .env
          echo VITE_TELEGRAM_BOT_TOKEN="${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}" >> .env
          echo VITE_TELEGRAM_CHAT_ID="${{ secrets.VITE_TELEGRAM_CHAT_ID }}" >> .env
          echo "Content of .env file (with masked values):"
          cat .env | sed 's/=.*$/=***/'

      - name: Build with Vite
        env:
          VITE_TELEGRAM_BOT_TOKEN: ${{ secrets.VITE_TELEGRAM_BOT_TOKEN }}
          VITE_TELEGRAM_CHAT_ID: ${{ secrets.VITE_TELEGRAM_CHAT_ID }}
        run: |
          echo "Build environment check:"
          env | grep VITE_ | sed 's/=.*$/=***/'
          npm run build

      - name: Check build output
        run: |
          echo "Checking build output directory:"
          ls -la dist/
          echo "Checking for environment variables in main chunk:"
          grep -r "VITE_" dist/ || echo "No direct VITE_ strings found in build"

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4